version: '3.1'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
  api:
    image: mb/api
    build:
      context: .
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=root
      - DATABASE_PORT=5432
      - DATABASE_NAME=postgres
      - TZ='America/Fortaleza'
    ports:
      - "3000:3000"